/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#90d1e0",
        "on-tertiary-fixed": "#1f0a52",
        "on-tertiary-container": "#3d2c71",
        "on-surface-variant": "#404752",
        "surface-container-high": "#e6e8ec",
        "tertiary": "#63539a",
        "on-primary-container": "#003a67",
        "on-secondary": "#ffffff",
        "surface-container": "#eceef2",
        "on-secondary-fixed": "#001f25",
        "surface-tint": "#0061a5",
        "inverse-on-surface": "#eff1f5",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001c37",
        "surface": "#f7f9fd",
        "surface-bright": "#f7f9fd",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary-container": "#acedfd",
        "on-error-container": "#93000a",
        "on-secondary-container": "#286d7b",
        "on-surface": "#181c1f",
        "tertiary-fixed-dim": "#cdbdff",
        "secondary-fixed": "#acedfd",
        "tertiary-fixed": "#e7deff",
        "error": "#ba1a1a",
        "inverse-surface": "#2d3134",
        "primary-fixed": "#d2e4ff",
        "surface-container-highest": "#e0e3e6",
        "on-secondary-fixed-variant": "#004e5b",
        "on-error": "#ffffff",
        "primary": "#0061a5",
        "primary-fixed-dim": "#a0caff",
        "inverse-primary": "#a0caff",
        "outline-variant": "#c0c7d4",
        "on-primary-fixed-variant": "#00497e",
        "outline": "#707783",
        "secondary": "#206775",
        "background": "#f7f9fd",
        "surface-variant": "#e0e3e6",
        "surface-dim": "#d8dade",
        "tertiary-container": "#a897e3",
        "on-tertiary-fixed-variant": "#4b3b80",
        "surface-container-low": "#f2f4f8",
        "primary-container": "#4da6ff",
        "on-background": "#181c1f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "margin-desktop": "64px",
        "container-max": "1440px",
        "unit": "8px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "inter": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "headline-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["32px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "display": ["72px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800" }],
        "label-bold": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "letterSpacing": "0", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
